---
- name: Create caddy systemd service
  template:
    src: caddy.service.j2
    dest: "{{ systemd_service_dir }}/{{ caddy_service_name }}.service"
    owner: root
    group: root
    mode: 0755

- name: Start caddy systemd service
  systemd:
    name: "{{ caddy_service_name }}"
    enabled: yes
    daemon-reload: yes
    state: started